#!/bin/sh

make_resolv_conf() {
    local R
    local nameserver
    for nameserver in $new_domain_name_servers ; do
        R="${R}nameserver $nameserver
"
    done

    for nameserver in $new_dhcp6_name_servers ; do
        # If the nameserver has a link-local address
        # then add a zone ID (interface name) to it.
        case "$nameserver" in
            fe80::|FE80::)
                zone_id="%$interface"
                ;;
            *)
                zone_id=""
        esac
        R="${R}nameserver $nameserver$zone_id
"
    done

    [ -z "$R" ] || echo -n "$R" > /etc/resolv.conf.dhclient
}
