#!/bin/sh

set -e

cd "$(dirname "$(readlink -f "$0")")"
[ x"${USER}" = x"root" ] || \
    SUDO=sudo

[ ! -f .git/refs/heads/private ] || {
    git checkout private
    EDITOR=true git merge master
}

$SUDO puppet apply \
    --confdir=$PWD \
    --modulepath=$PWD/local-modules:$PWD/modules:/usr/share/puppet/modules \
    "${@:---test}" \
    manifests/site.pp
