#!/bin/sh

screen="card0-HDMI-A-3"

for i in $(seq 1 3); do
    [ x"$(cat /sys/class/drm/$screen/status)" = x"connected" ] || {
        >&2 echo "Screen $screen is disconnected, do not start now"
        exit 3
    }
    sleep 1
done

exec sudo -u xbmc env \
    AE_SINK=ALSE \
    /usr/bin/xinit /usr/bin/xbmc-standalone -- :0
